<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // USERS
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Sarah Wijaya',
                'email' => 'sarah.wijaya@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Rizki Pratama',
                'email' => 'rizki.pratama@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Maya Kusuma',
                'email' => 'maya.kusuma@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Dimas Anggara',
                'email' => 'dimas.anggara@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Putri Maharani',
                'email' => 'putri.maharani@gmail.com',
                'password' => Hash::make('password'),
                'role' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // PLACES
        DB::table('places')->insert([
            // Jakarta Places
            [
                'place_id' => 1,
                'name' => 'Kopi Kenangan Grand Indonesia',
                'address' => 'Grand Indonesia Mall, Jl. MH Thamrin No.1, Jakarta Pusat',
                'latitude' => -6.195396,
                'longitude' => 106.822998,
                'description' => 'Coffee shop dengan signature kopi susu kekinian',
                'category' => 'Cafe',
                'created_at' => now(),
            ],
            [
                'place_id' => 2,
                'name' => 'Monumen Nasional (Monas)',
                'address' => 'Jl. Silang Monas, Gambir, Jakarta Pusat',
                'latitude' => -6.175392,
                'longitude' => 106.827153,
                'description' => 'Monumen ikonik Jakarta dengan taman luas di sekitarnya',
                'category' => 'Wisata',
                'created_at' => now(),
            ],
            [
                'place_id' => 3,
                'name' => 'Central Park Mall',
                'address' => 'Jl. Letjen S. Parman Kav.28, Jakarta Barat',
                'latitude' => -6.178306,
                'longitude' => 106.790810,
                'description' => 'Mall modern dengan berbagai tenant dan area kuliner',
                'category' => 'Mall',
                'created_at' => now(),
            ],
            [
                'place_id' => 4,
                'name' => 'Sate Khas Senayan',
                'address' => 'Plaza Senayan, Jl. Asia Afrika Lot.19, Jakarta Selatan',
                'latitude' => -6.225825,
                'longitude' => 106.799389,
                'description' => 'Restoran sate dan masakan Indonesia dengan cita rasa autentik',
                'category' => 'Restaurant',
                'created_at' => now(),
            ],
            [
                'place_id' => 5,
                'name' => 'SPBU Pertamina Gatot Subroto',
                'address' => 'Jl. Gatot Subroto, Jakarta Selatan',
                'latitude' => -6.224140,
                'longitude' => 106.827940,
                'description' => 'SPBU strategis untuk isi bensin',
                'category' => 'Gas Station',
                'created_at' => now(),
            ],
            // Bandung Places
            [
                'place_id' => 6,
                'name' => 'Trans Studio Bandung',
                'address' => 'Jl. Gatot Subroto No.289, Bandung',
                'latitude' => -6.927074,
                'longitude' => 107.637253,
                'description' => 'Theme park indoor terbesar di Indonesia',
                'category' => 'Wisata',
                'created_at' => now(),
            ],
            [
                'place_id' => 7,
                'name' => 'Factory Outlet Rumah Mode',
                'address' => 'Jl. Setiabudhi No.41, Bandung',
                'latitude' => -6.869932,
                'longitude' => 107.597778,
                'description' => 'Factory outlet dengan berbagai brand fashion',
                'category' => 'Shopping',
                'created_at' => now(),
            ],
            [
                'place_id' => 8,
                'name' => 'Hotel Jayakarta Bandung',
                'address' => 'Jl. Ir. H. Juanda No.381A, Bandung',
                'latitude' => -6.907763,
                'longitude' => 107.600494,
                'description' => 'Hotel bintang 4 dengan pemandangan kota Bandung',
                'category' => 'Hotel',
                'created_at' => now(),
            ],
            [
                'place_id' => 9,
                'name' => 'Warung Nasi Ampera',
                'address' => 'Jl. Veteran No.25, Bandung',
                'latitude' => -6.912273,
                'longitude' => 107.610894,
                'description' => 'Restoran masakan Padang legendaris di Bandung',
                'category' => 'Restaurant',
                'created_at' => now(),
            ],
            [
                'place_id' => 10,
                'name' => 'Indomaret Dago',
                'address' => 'Jl. Ir. H. Juanda No.120, Bandung',
                'latitude' => -6.897760,
                'longitude' => 107.612580,
                'description' => 'Minimarket untuk beli kebutuhan sehari-hari',
                'category' => 'Minimarket',
                'created_at' => now(),
            ],
            // Yogyakarta Places
            [
                'place_id' => 11,
                'name' => 'Malioboro Mall',
                'address' => 'Jl. Malioboro No.52-58, Yogyakarta',
                'latitude' => -7.792531,
                'longitude' => 110.365463,
                'description' => 'Pusat perbelanjaan di jantung kota Yogyakarta',
                'category' => 'Mall',
                'created_at' => now(),
            ],
            [
                'place_id' => 12,
                'name' => 'Candi Prambanan',
                'address' => 'Jl. Raya Solo-Yogyakarta No.16, Sleman',
                'latitude' => -7.752020,
                'longitude' => 110.491467,
                'description' => 'Kompleks candi Hindu terbesar di Indonesia',
                'category' => 'Wisata',
                'created_at' => now(),
            ],
            [
                'place_id' => 13,
                'name' => 'Gudeg Yu Djum',
                'address' => 'Jl. Wijilan No.167, Yogyakarta',
                'latitude' => -7.802813,
                'longitude' => 110.365760,
                'description' => 'Rumah makan gudeg terkenal dengan cita rasa khas Yogya',
                'category' => 'Restaurant',
                'created_at' => now(),
            ],
            [
                'place_id' => 14,
                'name' => 'The Phoenix Hotel Yogyakarta',
                'address' => 'Jl. Jenderal Sudirman No.9, Yogyakarta',
                'latitude' => -7.783640,
                'longitude' => 110.390876,
                'description' => 'Hotel heritage dengan arsitektur kolonial yang indah',
                'category' => 'Hotel',
                'created_at' => now(),
            ],
            [
                'place_id' => 15,
                'name' => 'Rental Mobil Jogja Transport',
                'address' => 'Jl. Magelang No.15, Yogyakarta',
                'latitude' => -7.797068,
                'longitude' => 110.370529,
                'description' => 'Jasa rental mobil dengan driver berpengalaman',
                'category' => 'Transport',
                'created_at' => now(),
            ],
            // Surabaya Places
            [
                'place_id' => 16,
                'name' => 'Tunjungan Plaza',
                'address' => 'Jl. Basuki Rahmat No.8-12, Surabaya',
                'latitude' => -7.262744,
                'longitude' => 112.738251,
                'description' => 'Mall besar di pusat kota Surabaya',
                'category' => 'Mall',
                'created_at' => now(),
            ],
            [
                'place_id' => 17,
                'name' => 'Rawon Setan',
                'address' => 'Jl. Embong Malang No.78, Surabaya',
                'latitude' => -7.268600,
                'longitude' => 112.743530,
                'description' => 'Warung rawon legendaris yang buka malam hari',
                'category' => 'Restaurant',
                'created_at' => now(),
            ],
            [
                'place_id' => 18,
                'name' => 'House of Sampoerna',
                'address' => 'Jl. Taman Sampoerna No.6, Surabaya',
                'latitude' => -7.245340,
                'longitude' => 112.740440,
                'description' => 'Museum sejarah rokok kretek Sampoerna',
                'category' => 'Museum',
                'created_at' => now(),
            ],
            [
                'place_id' => 19,
                'name' => 'Hotel Majapahit Surabaya',
                'address' => 'Jl. Tunjungan No.65, Surabaya',
                'latitude' => -7.265620,
                'longitude' => 112.739580,
                'description' => 'Hotel mewah bersejarah dengan arsitektur kolonial',
                'category' => 'Hotel',
                'created_at' => now(),
            ],
            [
                'place_id' => 20,
                'name' => 'Cinema XXI Tunjungan Plaza',
                'address' => 'Tunjungan Plaza 4 Lt.3, Surabaya',
                'latitude' => -7.262744,
                'longitude' => 112.738251,
                'description' => 'Bioskop modern di dalam mall',
                'category' => 'Cinema',
                'created_at' => now(),
            ],
        ]);

        // EVENTS
        DB::table('events')->insert([
            [
                'event_id' => 1,
                'event_name' => 'Weekend Gathering Jakarta',
                'description' => 'Ngumpul santai di Jakarta sambil makan dan jalan-jalan',
                'event_date' => '2024-11-18',
                'creator_id' => 1,
                'status' => 'completed',
                'created_at' => now()->subDays(45),
            ],
            [
                'event_id' => 2,
                'event_name' => 'Bandung Adventure Trip',
                'description' => 'Liburan 2 hari 1 malam ke Bandung untuk belanja dan wisata',
                'event_date' => '2024-10-10',
                'creator_id' => 2,
                'status' => 'completed',
                'created_at' => now()->subDays(70),
            ],
            [
                'event_id' => 3,
                'event_name' => 'Yogyakarta Cultural Tour',
                'description' => 'Explore budaya dan kuliner Yogyakarta selama 3 hari',
                'event_date' => '2024-09-20',
                'creator_id' => 3,
                'status' => 'completed',
                'created_at' => now()->subDays(90),
            ],
            [
                'event_id' => 4,
                'event_name' => 'Surabaya Culinary Experience',
                'description' => 'Wisata kuliner dan sejarah di Surabaya 2 hari 1 malam',
                'event_date' => '2024-08-15',
                'creator_id' => 4,
                'status' => 'completed',
                'created_at' => now()->subDays(125),
            ],
        ]);

        // EVENT PARTICIPANTS
        DB::table('event_participants')->insert([
            // Event 1: Weekend Gathering Jakarta
            ['event_id' => 1, 'user_id' => 1, 'joined_at' => now()->subDays(45)],
            ['event_id' => 1, 'user_id' => 2, 'joined_at' => now()->subDays(44)],
            ['event_id' => 1, 'user_id' => 3, 'joined_at' => now()->subDays(44)],
            
            // Event 2: Bandung Adventure Trip
            ['event_id' => 2, 'user_id' => 2, 'joined_at' => now()->subDays(70)],
            ['event_id' => 2, 'user_id' => 4, 'joined_at' => now()->subDays(69)],
            ['event_id' => 2, 'user_id' => 5, 'joined_at' => now()->subDays(69)],
            
            // Event 3: Yogyakarta Cultural Tour
            ['event_id' => 3, 'user_id' => 3, 'joined_at' => now()->subDays(90)],
            ['event_id' => 3, 'user_id' => 1, 'joined_at' => now()->subDays(89)],
            ['event_id' => 3, 'user_id' => 5, 'joined_at' => now()->subDays(89)],
            
            // Event 4: Surabaya Culinary Experience
            ['event_id' => 4, 'user_id' => 4, 'joined_at' => now()->subDays(125)],
            ['event_id' => 4, 'user_id' => 1, 'joined_at' => now()->subDays(124)],
            ['event_id' => 4, 'user_id' => 2, 'joined_at' => now()->subDays(124)],
        ]);

        // ACTIVITIES
        DB::table('activities')->insert([
            // Event 1: Weekend Gathering Jakarta
            [
                'activity_id' => 1,
                'event_id' => 1,
                'place_id' => 1,
                'title' => 'Food & Drinks',
                'description' => 'Kumpul pagi sambil ngopi dan sarapan ringan',
                'start_time' => '2024-11-18 09:00:00',
                'end_time' => '2024-11-18 10:30:00',
                'order_number' => 1,
            ],
            [
                'activity_id' => 2,
                'event_id' => 1,
                'place_id' => 2,
                'title' => 'Tickets & Entrance',
                'description' => 'Jalan-jalan ke Monas dan naik ke puncak monumen',
                'start_time' => '2024-11-18 11:00:00',
                'end_time' => '2024-11-18 13:00:00',
                'order_number' => 2,
            ],
            [
                'activity_id' => 3,
                'event_id' => 1,
                'place_id' => 4,
                'title' => 'Food & Drinks',
                'description' => 'Makan siang bareng di restoran Sate Senayan',
                'start_time' => '2024-11-18 13:30:00',
                'end_time' => '2024-11-18 15:00:00',
                'order_number' => 3,
            ],
            [
                'activity_id' => 4,
                'event_id' => 1,
                'place_id' => 3,
                'title' => 'Shopping',
                'description' => 'Belanja oleh-oleh dan jalan-jalan di mall',
                'start_time' => '2024-11-18 15:30:00',
                'end_time' => '2024-11-18 18:00:00',
                'order_number' => 4,
            ],
            [
                'activity_id' => 5,
                'event_id' => 1,
                'place_id' => 5,
                'title' => 'Transport',
                'description' => 'Isi bensin untuk perjalanan pulang',
                'start_time' => '2024-11-18 18:15:00',
                'end_time' => '2024-11-18 18:30:00',
                'order_number' => 5,
            ],
            
            // Event 2: Bandung Adventure Trip
            [
                'activity_id' => 6,
                'event_id' => 2,
                'place_id' => 5,
                'title' => 'Transport',
                'description' => 'Isi bensin sebelum berangkat ke Bandung',
                'start_time' => '2024-10-10 06:00:00',
                'end_time' => '2024-10-10 06:15:00',
                'order_number' => 1,
            ],
            [
                'activity_id' => 7,
                'event_id' => 2,
                'place_id' => 8,
                'title' => 'Accommodation',
                'description' => 'Check-in hotel untuk menginap 1 malam',
                'start_time' => '2024-10-10 10:00:00',
                'end_time' => '2024-10-11 12:00:00',
                'order_number' => 2,
            ],
            [
                'activity_id' => 8,
                'event_id' => 2,
                'place_id' => 9,
                'title' => 'Food & Drinks',
                'description' => 'Makan siang masakan Padang',
                'start_time' => '2024-10-10 12:30:00',
                'end_time' => '2024-10-10 14:00:00',
                'order_number' => 3,
            ],
            [
                'activity_id' => 9,
                'event_id' => 2,
                'place_id' => 7,
                'title' => 'Shopping',
                'description' => 'Belanja baju dan souvenir di factory outlet',
                'start_time' => '2024-10-10 14:30:00',
                'end_time' => '2024-10-10 17:00:00',
                'order_number' => 4,
            ],
            [
                'activity_id' => 10,
                'event_id' => 2,
                'place_id' => 6,
                'title' => 'Tickets & Entrance',
                'description' => 'Bermain di Trans Studio Bandung',
                'start_time' => '2024-10-10 18:00:00',
                'end_time' => '2024-10-10 21:00:00',
                'order_number' => 5,
            ],
            [
                'activity_id' => 11,
                'event_id' => 2,
                'place_id' => 10,
                'title' => 'Shared Items',
                'description' => 'Beli air minum galon dan snack untuk di hotel',
                'start_time' => '2024-10-10 21:30:00',
                'end_time' => '2024-10-10 22:00:00',
                'order_number' => 6,
            ],
            
            // Event 3: Yogyakarta Cultural Tour
            [
                'activity_id' => 12,
                'event_id' => 3,
                'place_id' => 15,
                'title' => 'Transport',
                'description' => 'Sewa mobil untuk keliling Yogyakarta 3 hari',
                'start_time' => '2024-09-20 08:00:00',
                'end_time' => '2024-09-22 20:00:00',
                'order_number' => 1,
            ],
            [
                'activity_id' => 13,
                'event_id' => 3,
                'place_id' => 14,
                'title' => 'Accommodation',
                'description' => 'Menginap di hotel heritage 2 malam',
                'start_time' => '2024-09-20 14:00:00',
                'end_time' => '2024-09-22 12:00:00',
                'order_number' => 2,
            ],
            [
                'activity_id' => 14,
                'event_id' => 3,
                'place_id' => 12,
                'title' => 'Tickets & Entrance',
                'description' => 'Tiket masuk Candi Prambanan dan tour guide',
                'start_time' => '2024-09-20 15:00:00',
                'end_time' => '2024-09-20 17:30:00',
                'order_number' => 3,
            ],
            [
                'activity_id' => 15,
                'event_id' => 3,
                'place_id' => 13,
                'title' => 'Food & Drinks',
                'description' => 'Makan malam gudeg khas Yogyakarta',
                'start_time' => '2024-09-20 18:30:00',
                'end_time' => '2024-09-20 20:00:00',
                'order_number' => 4,
            ],
            [
                'activity_id' => 16,
                'event_id' => 3,
                'place_id' => 11,
                'title' => 'Shopping',
                'description' => 'Belanja oleh-oleh khas Jogja di Malioboro',
                'start_time' => '2024-09-21 10:00:00',
                'end_time' => '2024-09-21 12:30:00',
                'order_number' => 5,
            ],
            [
                'activity_id' => 17,
                'event_id' => 3,
                'place_id' => 14,
                'title' => 'Entertainment / Fun',
                'description' => 'Karaoke bareng di lounge hotel',
                'start_time' => '2024-09-21 20:00:00',
                'end_time' => '2024-09-21 23:00:00',
                'order_number' => 6,
            ],
            
            // Event 4: Surabaya Culinary Experience
            [
                'activity_id' => 18,
                'event_id' => 4,
                'place_id' => 5,
                'title' => 'Transport',
                'description' => 'Isi bensin untuk perjalanan Jakarta-Surabaya',
                'start_time' => '2024-08-15 05:30:00',
                'end_time' => '2024-08-15 05:45:00',
                'order_number' => 1,
            ],
            [
                'activity_id' => 19,
                'event_id' => 4,
                'place_id' => 19,
                'title' => 'Accommodation',
                'description' => 'Check-in Hotel Majapahit untuk 1 malam',
                'start_time' => '2024-08-15 14:00:00',
                'end_time' => '2024-08-16 12:00:00',
                'order_number' => 2,
            ],
            [
                'activity_id' => 20,
                'event_id' => 4,
                'place_id' => 17,
                'title' => 'Food & Drinks',
                'description' => 'Makan rawon setan yang legendaris',
                'start_time' => '2024-08-15 19:00:00',
                'end_time' => '2024-08-15 20:30:00',
                'order_number' => 3,
            ],
            [
                'activity_id' => 21,
                'event_id' => 4,
                'place_id' => 18,
                'title' => 'Tickets & Entrance',
                'description' => 'Tour museum House of Sampoerna',
                'start_time' => '2024-08-16 09:00:00',
                'end_time' => '2024-08-16 11:00:00',
                'order_number' => 4,
            ],
            [
                'activity_id' => 22,
                'event_id' => 4,
                'place_id' => 16,
                'title' => 'Shopping',
                'description' => 'Belanja oleh-oleh khas Surabaya di Tunjungan Plaza',
                'start_time' => '2024-08-16 13:00:00',
                'end_time' => '2024-08-16 15:30:00',
                'order_number' => 5,
            ],
            [
                'activity_id' => 23,
                'event_id' => 4,
                'place_id' => 20,
                'title' => 'Entertainment / Fun',
                'description' => 'Nonton film bareng di bioskop',
                'start_time' => '2024-08-16 16:00:00',
                'end_time' => '2024-08-16 18:30:00',
                'order_number' => 6,
            ],
        ]);

        // EXPENSES
        DB::table('expenses')->insert([
            // Event 1: Weekend Gathering Jakarta
            [
                'expense_id' => 1,
                'event_id' => 1,
                'activity_id' => 1,
                'description' => 'Kopi dan breakfast menu untuk 3 orang',
                'amount' => 285000,
                'paid_by_user_id' => 1,
                'expense_date' => '2024-11-18',
            ],
            [
                'expense_id' => 2,
                'event_id' => 1,
                'activity_id' => 2,
                'description' => 'Tiket masuk Monas 3 orang @ 15rb',
                'amount' => 45000,
                'paid_by_user_id' => 2,
                'expense_date' => '2024-11-18',
            ],
            [
                'expense_id' => 3,
                'event_id' => 1,
                'activity_id' => 3,
                'description' => 'Makan siang sate dan nasi goreng',
                'amount' => 520000,
                'paid_by_user_id' => 3,
                'expense_date' => '2024-11-18',
            ],
            [
                'expense_id' => 4,
                'event_id' => 1,
                'activity_id' => 4,
                'description' => 'Belanja baju dan aksesoris',
                'amount' => 750000,
                'paid_by_user_id' => 1,
                'expense_date' => '2024-11-18',
            ],
            [
                'expense_id' => 5,
                'event_id' => 1,
                'activity_id' => 5,
                'description' => 'Bensin Pertalite 20 liter',
                'amount' => 200000,
                'paid_by_user_id' => 2,
                'expense_date' => '2024-11-18',
            ],
            
            // Event 2: Bandung Adventure Trip
            [
                'expense_id' => 6,
                'event_id' => 2,
                'activity_id' => 6,
                'description' => 'Bensin full tank untuk Jakarta-Bandung',
                'amount' => 450000,
                'paid_by_user_id' => 2,
                'expense_date' => '2024-10-10',
            ],
            [
                'expense_id' => 7,
                'event_id' => 2,
                'activity_id' => 7,
                'description' => 'Kamar hotel deluxe 2 kamar untuk 1 malam',
                'amount' => 1800000,
                'paid_by_user_id' => 5,
                'expense_date' => '2024-10-10',
            ],
            [
                'expense_id' => 8,
                'event_id' => 2,
                'activity_id' => 8,
                'description' => 'Makan siang nasi padang 3 porsi',
                'amount' => 375000,
                'paid_by_user_id' => 2,
                'expense_date' => '2024-10-10',
            ],
            [
                'expense_id' => 9,
                'event_id' => 2,
                'activity_id' => 9,
                'description' => 'Belanja baju dan jacket di FO',
                'amount' => 1250000,
                'paid_by_user_id' => 4,
                'expense_date' => '2024-10-10',
            ],
            [
                'expense_id' => 10,
                'event_id' => 2,
                'activity_id' => 10,
                'description' => 'Tiket Trans Studio 3 orang',
                'amount' => 750000,
                'paid_by_user_id' => 5,
                'expense_date' => '2025-02-10',
            ],
            [
                'expense_id' => 11,
                'event_id' => 2,
                'activity_id' => 10,
                'description' => 'Air galon dan snack untuk hotel',
                'amount' => 85000,
                'paid_by_user_id' => 2,
                'expense_date' => '2025-02-10',
            ],
            
            // Event 3: Yogyakarta Cultural Tour
            [
                'expense_id' => 12,
                'event_id' => 3,
                'activity_id' => 11,
                'description' => 'Rental mobil Avanza 3 hari termasuk driver',
                'amount' => 1500000,
                'paid_by_user_id' => 3,
                'expense_date' => '2024-12-20',
            ],
            [
                'expense_id' => 13,
                'event_id' => 3,
                'activity_id' => 11,
                'description' => 'Bensin dan parkir selama di Yogya',
                'amount' => 320000,
                'paid_by_user_id' => 1,
                'expense_date' => '2024-12-20',
            ],
            [
                'expense_id' => 14,
                'event_id' => 3,
                'activity_id' => 12,
                'description' => 'Hotel Phoenix 2 kamar untuk 2 malam',
                'amount' => 3200000,
                'paid_by_user_id' => 5,
                'expense_date' => '2024-12-20',
            ],
            [
                'expense_id' => 15,
                'event_id' => 3,
                'activity_id' => 13,
                'description' => 'Tiket Prambanan 3 orang + guide',
                'amount' => 225000,
                'paid_by_user_id' => 3,
                'expense_date' => '2024-12-20',
            ],
            [
                'expense_id' => 16,
                'event_id' => 3,
                'activity_id' => 14,
                'description' => 'Makan gudeg komplit 3 porsi',
                'amount' => 180000,
                'paid_by_user_id' => 1,
                'expense_date' => '2024-12-20',
            ],
            [
                'expense_id' => 17,
                'event_id' => 3,
                'activity_id' => 15,
                'description' => 'Oleh-oleh bakpia, gudeg kaleng, dan batik',
                'amount' => 850000,
                'paid_by_user_id' => 5,
                'expense_date' => '2024-12-21',
            ],
            [
                'expense_id' => 18,
                'event_id' => 3,
                'activity_id' => 16,
                'description' => 'Sewa speaker bluetooth untuk karaoke',
                'amount' => 150000,
                'paid_by_user_id' => 3,
                'expense_date' => '2024-12-21',
            ],
        ]);

        // USER PLACE VISITS
        DB::table('user_place_visits')->insert([
            // Sarah Wijaya visits
            [
                'user_id' => 1,
                'place_id' => 1,
                'visit_count' => 5,
                'last_visit_date' => '2025-01-18',
            ],
            [
                'user_id' => 1,
                'place_id' => 2,
                'visit_count' => 3,
                'last_visit_date' => '2025-01-18',
            ],
            [
                'user_id' => 1,
                'place_id' => 10,
                'visit_count' => 2,
                'last_visit_date' => '2024-12-20',
            ],
            [
                'user_id' => 1,
                'place_id' => 11,
                'visit_count' => 2,
                'last_visit_date' => '2024-12-20',
            ],
            
            // Rizki Pratama visits
            [
                'user_id' => 2,
                'place_id' => 1,
                'visit_count' => 4,
                'last_visit_date' => '2025-01-18',
            ],
            [
                'user_id' => 2,
                'place_id' => 2,
                'visit_count' => 1,
                'last_visit_date' => '2025-01-18',
            ],
            [
                'user_id' => 2,
                'place_id' => 5,
                'visit_count' => 1,
                'last_visit_date' => '2025-02-10',
            ],
            [
                'user_id' => 2,
                'place_id' => 6,
                'visit_count' => 3,
                'last_visit_date' => '2025-02-10',
            ],
            
            // Maya Kusuma visits
            [
                'user_id' => 3,
                'place_id' => 4,
                'visit_count' => 2,
                'last_visit_date' => '2025-01-18',
            ],
            [
                'user_id' => 3,
                'place_id' => 9,
                'visit_count' => 4,
                'last_visit_date' => '2024-12-21',
            ],
            [
                'user_id' => 3,
                'place_id' => 10,
                'visit_count' => 1,
                'last_visit_date' => '2024-12-20',
            ],
            [
                'user_id' => 3,
                'place_id' => 12,
                'visit_count' => 2,
                'last_visit_date' => '2024-12-20',
            ],
            
            // Dimas Anggara visits
            [
                'user_id' => 4,
                'place_id' => 6,
                'visit_count' => 2,
                'last_visit_date' => '2025-02-10',
            ],
            [
                'user_id' => 4,
                'place_id' => 7,
                'visit_count' => 1,
                'last_visit_date' => '2025-02-10',
            ],
            [
                'user_id' => 4,
                'place_id' => 8,
                'visit_count' => 1,
                'last_visit_date' => '2025-02-10',
            ],
            
            // Putri Maharani visits
            [
                'user_id' => 5,
                'place_id' => 5,
                'visit_count' => 2,
                'last_visit_date' => '2025-02-10',
            ],
            [
                'user_id' => 5,
                'place_id' => 9,
                'visit_count' => 3,
                'last_visit_date' => '2024-12-21',
            ],
            [
                'user_id' => 5,
                'place_id' => 11,
                'visit_count' => 1,
                'last_visit_date' => '2024-12-20',
            ],
        ]);

        $this->call([
            PlaceSeeder::class,
            RundownSeeder::class,
        ]);
    }
}